# Generated by Django 4.2.6 on 2023-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("kota", models.CharField(blank=True, max_length=100)),
                ("kelurahan", models.CharField(blank=True, max_length=100)),
                ("kecamatan", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("tipe", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reading_value", models.FloatField()),
                ("tipe", models.CharField(max_length=100)),
                ("reading_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pos_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.pos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Predict",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("predict_value", models.FloatField()),
                ("predict_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pos_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.pos"
                    ),
                ),
            ],
        ),
    ]
