# Generated by Django 4.2.6 on 2023-10-18 13:17

from django.db import migrations
from base.models import Pos, Reading
from datetime import datetime, timedelta
import pytz
import random

def create_Reading_dummy_data(apps, schema_editor):
    all_pos = Pos.objects.all()

    reading_datetime = datetime.utcnow()
    utc_timezone = pytz.timezone("UTC")
    reading_datetime = utc_timezone.localize(reading_datetime)

    for i in range(10):

        reading_datetime += timedelta(minutes=15)

        for pos in all_pos:
            if pos.tipe == "CurahHujan":
                reading_type = "CurahHujan"
            elif pos.tipe == "DugaAir":
                reading_type = "TinggiAir"
            else:
                reading_type = "Undefined"
            Reading.objects.create(pos_id = pos.id, reading_value = random.uniform(0,1000), tipe = reading_type, reading_at = reading_datetime)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_reading_reading_at"),
    ]

    operations = [migrations.RunPython(create_Reading_dummy_data)]
