# Generated by Django 4.2.6 on 2023-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_pos_reading_predict")
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
