# Generated by Django 4.2.6 on 2023-10-18 15:14

from django.db import migrations
from base.models import Predict, Reading, Pos
import random
from datetime import timedelta

def create_Predict_dummy_data(apps, schema_editor):
    tinggi_air_readings = Reading.objects.filter(tipe = "TinggiAir")

    for reading in tinggi_air_readings:
        Predict.objects.create(pos_id = reading.pos_id, predict_value = random.uniform(0,1000), predict_for = reading.reading_at + timedelta(minutes=15))

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_auto_20231018_2017"),
    ]

    operations = [migrations.RunPython(create_Predict_dummy_data)]
